import { join } from "path";

const swaggerJsdoc = require('swagger-jsdoc');
const options = {
    // List of files to be processed.
    apis: [join(__dirname, '../../src/controllers/user.controller.ts')],
    // You can also set globs for your apis
    // e.g. './routes/*.js'
    schemes:['http'],
    basePath: '/',
    swaggerDefinition: {
        info: {
            description: 'Test API with autogenerated swagger doc',
            swagger: '2.0',
            title: 'Dessert API',
            version: '1.0.0',
        },
    },
};
const specs = swaggerJsdoc(options);
specs.schemes = ['http']
export default specs;