# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sustain CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install and build common package
      run: |
        cd packages/common
        npm i 
        npm run build
    - name: install and build core package
      run: |
        cd packages/core
        npm i 
        npm run build
    - name: install and build extension sessions package
      run: |
        cd packages/extensions/sessions
        npm i 
        npm run build
    - name: install and test basic router package
      run: |
        cd samples/basic-routers
        npm i 
        npm run build
                 
      env:
        CI: true  
      
    - uses: codecov/codecov-action@v1
